import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:login_page/DashBoard.dart';
import 'package:login_page/Register.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'config.dart';

class SignInPage extends StatefulWidget {
  const SignInPage({super.key});

  @override
  State<SignInPage> createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  TextEditingController emailController = TextEditingController();
  TextEditingController passwordController = TextEditingController();
  bool _isValid = false;

  late SharedPreferences prefs;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    initSharedPref();
  }

  void initSharedPref() async {
    prefs = await SharedPreferences.getInstance();
  }

  //takes data from fields nd send back to backend
  void loginUser() async {
    if (emailController.text.isNotEmpty && passwordController.text.isNotEmpty) {
      //object for passing data in backend
      var regBody = {
        "email": emailController.text,
        "password": passwordController.text,
      };

      try {
        //sending through post api to our localhost(regsiter)
        var response = await http.post(
          Uri.parse(login),
          //what kind of data sendind to backend
          headers: {
            "Content-Type": "application/json", // must be inside http.post()
          },
          // convert map to JSON string(bcz object direcly can't be send)
          body: jsonEncode(regBody), // convert map -> JSON string
        );
        var jsonResponse = jsonDecode(response.body);

        if (jsonResponse['status']) {
          //shared prefernces stored our token generated by login form
          var myToken = jsonResponse['token'];
          prefs.setString('token', myToken);
          //navigate to dashboard
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => Dashboard(token: myToken)),
          );
        } else {
          print('Something went wrong');
        }
      } catch (e) {
        print("Error: $e");
      }
    } else {
      setState(() {
        _isValid = true;
      });
    }
  }

  void signUp() {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (context) => Register()),
    );
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [Colors.blue, Colors.white],
            ),
          ),
          child: Center(
            child: SingleChildScrollView(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Text(
                    'Sign in',
                    style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 20),
                  Container(
                    width: MediaQuery.of(context).size.width * 0.8,
                    child: TextField(
                      controller: emailController,
                      keyboardType: TextInputType.emailAddress,
                      decoration: InputDecoration(
                        hintText: "Email",
                        errorText: _isValid ? "Enter required field" : null,
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(height: 20),
                  Container(
                    width: MediaQuery.of(context).size.width * 0.8,
                    child: TextField(
                      controller: passwordController,
                      keyboardType: TextInputType.text,
                      obscureText: true,
                      decoration: InputDecoration(
                        hintText: "Password",
                        errorText: _isValid ? "Enter required field" : null,
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(height: 20),
                  Container(
                    width: MediaQuery.of(context).size.width * 0.8,
                    child: ElevatedButton(
                      onPressed: () {
                        loginUser();
                      },
                      child: Text("Sign in"),
                    ),
                  ),
                  const SizedBox(height: 30),
                  Text("Don't have an account?"),
                  Container(
                    width: MediaQuery.of(context).size.width * 0.8,
                    child: TextButton(
                      onPressed: () {
                        signUp();
                      },
                      child: Text("Register"),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
